# only flake8 tests
# need to add pytest
name: test
on: 
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
        include:
        - os: macos-latest
          python-version: '3.11'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov pytest pytest-flake8        
        pip install -r dependencies.txt

    - name: Validate version
      run: python --version

    - name: Run simple python code
      run: python -c 'import math; print(math.factorial(5))'

    - name: Test with flake8
      run: |
        pip install flake8
        flake8 src/ --ignore=E501,W504,W503,E226,F401,E241,F405,F403
        flake8 Flaskapp/app/ --ignore=E501,W504,E226
